### ISSUE TITLE
Skin Information (NameMC Update?)

### ISSUE THREAD

**Issue by Grovel** [MrZillaGold/NameMCWrapper#520]
Can you update namemc skin info? they changed their site up a bit
issue with getSkin function

TypeError: ratingElement is not iterable
    at SkinContext._SkinContext_parseSkinCounters (C:\Users\Administrator\Desktop\Projects\NameMCOSINT\node_modules\namemcwrapper\dist\contexts\skin\index.js:361:14)
    at new SkinContext (C:\Users\Administrator\Desktop\Projects\NameMCOSINT\node_modules\namemcwrapper\dist\contexts\skin\index.js:142:112)
    at C:\Users\Administrator\Desktop\Projects\NameMCOSINT\node_modules\namemcwrapper\dist\contexts\skin\index.js:256:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SkinContext.loadPayload (C:\Users\Administrator\Desktop\Projects\NameMCOSINT\node_modules\namemcwrapper\dist\contexts\skin\index.js:253:20)
    at async NameMC.getSkin (C:\Users\Administrator\Desktop\Projects\NameMCOSINT\node_modules\namemcwrapper\dist\index.js:232:5)
    at async test (C:\Users\Administrator\Desktop\Projects\NameMCOSINT\app.js:9:22)

**Comment by MrZillaGold** [comment]
Thanks for report! I'll check later today.

**Comment by Grovel** [comment]
> Thanks for report! I'll check later today.

Thanks, could you also perhaps add the ability to get profile names from skins?

![image](https://user-images.githubusercontent.com/63136371/178472798-e1cfb06d-732a-4e7e-a601-186ca8ef532d.png)

**Comment by MrZillaGold** [comment]
> ability to get profile names from skins

I'll check, but it seems that the site does not return the list until the page is fully loaded (javascript files are connected), the library does not fully load the page, otherwise it would affect performance

**Comment by egorprnn** [comment]
The bug has been fixed (https://github.com/MrZillaGold/NameMCWrapper/releases/tag/2.4.2), it is possible to parse the list of players, but now I don’t have free time to implement the functionality.
Open a separate issue with a request for this functionality so that it is not lost.
